#!/usr/bin/env python3
"""
Effects of Age and Sex on group-level anatomical & functional results.

Mass-univariate test of diagnosis x age and diagnosis x sex interactions,
matching the manuscript section "The Effects of Age and Sex". For every
feature (anatomical region / functional edge) we fit, on Autism+NT only:

    age model:  y ~ C(diagnosis)*age_c + C(Sex)   + C(cohort)
    sex model:  y ~ C(diagnosis)*C(Sex) + age_c   + C(cohort)

and keep the single interaction coefficient. p-values are FDR-corrected
(Benjamini-Hochberg) across features, per modality x model, to match the
significance criterion used in the autism-vs-NT scripts. A feature "survives"
if its interaction p_fdr < 0.05.

Outputs (11_age_sex_analysis/outputs/):
  - interaction_<modality>_<model>.csv   per-feature betas/t/p/p_fdr
  - age_sex_interaction_summary.csv       one row per modality x model
"""

import os
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from statsmodels.stats.multitest import multipletests

warnings.filterwarnings('ignore')

# ---------------------------------------------------------------------------
# PATHS
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_SECTION_DIR = os.path.dirname(_SCRIPT_DIR)
OUTPUT_DIR = os.path.join(_SECTION_DIR, 'outputs')
Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

import sys
import importlib.util

# Reuse the curated anatomical pipeline's config + curated-clinical loader
# (curated_clinical mirrors 1_clustering/scripts/04_run_clustering_curated.py).
os.environ.setdefault('CURATED_CLINICAL', '1')  # phenotype from curated clinical TSVs
_CURATED_SCRIPTS = os.path.abspath(os.path.join(
    _SECTION_DIR, '..', '4_anatomical_analysis', 'curated', 'scripts'))
sys.path.insert(0, _CURATED_SCRIPTS)
import _config          # shared paths: MRI_FILE = anat input
import curated_clinical  # curated per-cohort clinical TSVs (population_group/age/sex)

# curated pipeline's script 01 (module name starts with a digit -> importlib):
# reuse its FreeSurfer column rename, wave dedup, and canonical join-key helpers.
_spec = importlib.util.spec_from_file_location(
    'anat01', os.path.join(_CURATED_SCRIPTS, '01_anatomical_mri_autism_nt_v2.py'))
anat01 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(anat01)

MRI_FILE = _config.MRI_FILE

LIB = '/Users/mfleury/POSTDOC/LIBRAIRY'
ANAT_FILE = MRI_FILE

# Age-bin robustness check only (09/10): ComBat + regression identical to
# ANAT_FILE except age/age2 are NOT regressed out (still passed to ComBat, so
# batch correction can't absorb age signal) -- age bins are the stratifying
# variable here, so testing on residuals that already had the linear age
# effect removed globally would be close to meaningless. Generated by
# eeg_mri-pipeline/analysis/mri/zscore_autism_td_analysis/pipeline_ndd/
# run_pipeline.py with REGRESS_AGE=0 QC_KEEP=1.
NOAGE_ANAT_FILE = os.path.join(os.path.dirname(MRI_FILE),
                                'freesurfer_zscore_qc1_combat_regress_noage.tsv')

# Must match the manuscript's primary rsfMRI pipeline: the run-concatenated
# (>6 min), no-GSR connectivity table in 6-2_functional_analysis (verified
# n=393 autism/327 NT, exactly the reported whole-cohort N) -- NOT
# 6_functional_analysis's df_conn_cohort_norm.csv (an older, non-concatenated
# table with a different sample, 355/295), which this pointed to previously.
FUNC_FILE = os.path.join(LIB, 'LEAP-InovAND_resource', '6-2_functional_analysis',
                         'preprocessing', 'outputs', 'nogsr_concat',
                         'df_conn_cohort_norm_nogsr_concat.csv')

# Phenotype/demographics for the ANAT models: the curated concat (population_group,
# age_yrs, Sex, cohort) written by 1_clustering curated pipeline.
CLINICAL_FILE = os.path.join(
    LIB, 'LEAP-InovAND_resource', '1_clustering', 'outputs', 'curated', 'tables',
    'individuals_metrics_with_clusters_curated_ward.csv')

FDR_ALPHA = 0.05


def _fit_feature(sub, formula):
    """Fit one OLS and return (beta, t, p) for the lone interaction term."""
    m = smf.ols(formula, sub).fit()
    inter = [p for p in m.params.index if ':' in p]
    if not inter:
        return None
    name = inter[0]  # binary x continuous / binary x binary -> single term
    return m.params[name], m.tvalues[name], m.pvalues[name], m.df_resid


def run_models(df, feature_cols, modality, family_of=None, cov_of=None):
    """Fit age and sex interaction models over all feature_cols.

    df must carry: diag ('NT'/'Autism'), age_c (centered yrs), Sex, cohort.
    family_of: optional feature->family map; FDR is corrected WITHIN each
    family (e.g. per anatomical metric, matching the autism-vs-NT pipeline).
    If None, a single FDR family spans all features.
    cov_of: optional feature->extra covariate column name (or None). Added
    additively to the model — used to regress out a global size measure
    (e.g. mean surface area / volume) so a global age x diagnosis scaling
    effect doesn't smear across regions.
    """
    base = ["diag", "age_c", "Sex", "cohort"]
    extra = sorted({cov_of(f) for f in feature_cols if cov_of and cov_of(f)}) if cov_of else []
    base = base + extra
    formulas = {
        # diagnosis x age, adjusting for sex + cohort
        "age": "y ~ C(diag, Treatment('NT')) * age_c + C(Sex) + C(cohort)",
        # diagnosis x sex, adjusting for age + cohort
        "sex": "y ~ C(diag, Treatment('NT')) * C(Sex) + age_c + C(cohort)",
    }

    summaries = []
    results = {}
    for model_name, base_formula in formulas.items():
        rows = []
        for feat in feature_cols:
            sub = df[[feat] + base].rename(columns={feat: 'y'}).dropna()
            # need both groups, both sexes, enough rows for the design
            if sub['diag'].nunique() < 2 or sub['Sex'].nunique() < 2 or len(sub) < 30:
                continue
            formula = base_formula
            if cov_of and cov_of(feat):
                formula = f"{formula} + Q('{cov_of(feat)}')"
            res = _fit_feature(sub, formula)
            if res is None:
                continue
            beta, t, p, df_resid = res
            # interaction effect size: t->d conversion, d = 2t/sqrt(df_resid)
            cohens_d = 2 * t / np.sqrt(df_resid) if df_resid > 0 else float('nan')
            rows.append({'feature': feat, 'n': len(sub),
                         'beta_interaction': beta, 't': t, 'p_value': p,
                         'cohens_d': cohens_d})

        res_df = pd.DataFrame(rows)
        if len(res_df):
            if family_of is not None:
                res_df['family'] = res_df['feature'].map(family_of)
                res_df['p_fdr'] = np.nan
                for _, idx in res_df.groupby('family').groups.items():
                    res_df.loc[idx, 'p_fdr'] = multipletests(
                        res_df.loc[idx, 'p_value'], method='fdr_bh')[1]
            else:
                res_df['p_fdr'] = multipletests(res_df['p_value'], method='fdr_bh')[1]
            res_df = res_df.sort_values('p_value')
            n_sig_unc = int((res_df['p_value'] < FDR_ALPHA).sum())
            n_sig_fdr = int((res_df['p_fdr'] < FDR_ALPHA).sum())
            min_p = float(res_df['p_value'].min())
            min_pfdr = float(res_df['p_fdr'].min())
            max_abs_d = float(res_df['cohens_d'].abs().max())
        else:
            res_df['p_fdr'] = []
            n_sig_unc = n_sig_fdr = 0
            min_p = min_pfdr = max_abs_d = float('nan')

        out = os.path.join(OUTPUT_DIR, f"interaction_{modality}_{model_name}.csv")
        res_df.to_csv(out, index=False)
        results[model_name] = res_df
        print(f"  [{modality}/{model_name}] features={len(res_df)}  "
              f"sig_uncorrected={n_sig_unc}  sig_FDR={n_sig_fdr}  "
              f"min_p={min_p:.3g}  min_p_fdr={min_pfdr:.3g}  "
              f"max|d|={max_abs_d:.3g}")

        summaries.append({
            'modality': modality, 'interaction': f'diagnosis x {model_name}',
            'n_features': len(res_df), 'n_sig_uncorrected_p05': n_sig_unc,
            'n_sig_fdr_05': n_sig_fdr, 'min_p_value': min_p, 'min_p_fdr': min_pfdr,
            'max_abs_cohens_d': max_abs_d, 'survives_criterion': n_sig_fdr > 0,
        })
    return summaries, results


def prep_common(df, pop_col):
    """Restrict to Autism/NT, recode diagnosis, center age."""
    df = df[df[pop_col].isin(['Autism', 'TD', 'NT'])].copy()
    df['diag'] = df[pop_col].replace('TD', 'NT')
    df = df[df['age_yrs'].notna() & df['Sex'].notna() & df['cohort'].notna()].copy()
    df['age_c'] = df['age_yrs'].astype(float) - df['age_yrs'].astype(float).mean()
    # patsy can't read pandas StringDtype (pandas may infer it on astype(str));
    # Categorical/float are safe.
    df['diag'] = pd.Categorical(df['diag'].map(str))
    df['cohort'] = pd.Categorical(df['cohort'].map(str))
    df['Sex'] = df['Sex'].astype(float)
    return df


def anat_feature_cols(df):
    """DK cortical (thickness/area/volume) + ASEG subcortical region columns."""
    # global cortical summaries carry the metric suffix in this file
    # (lh_WhiteSurfArea_area, lh_MeanThickness_thickness) -> exclude by substring
    dk = [c for c in df.columns
          if c.startswith(('lh_', 'rh_'))
          and c.endswith(('_thickness', '_area', '_volume'))
          and 'WhiteSurfArea' not in c and 'MeanThickness' not in c]
    aseg = [c for c in [
        'Left-Lateral-Ventricle', 'Left-Thalamus', 'Left-Caudate', 'Left-Putamen',
        'Left-Pallidum', '3rd-Ventricle', '4th-Ventricle', 'Brain-Stem',
        'Left-Hippocampus', 'Left-Amygdala', 'Left-VentralDC',
        'Right-Lateral-Ventricle', 'Right-Thalamus', 'Right-Caudate',
        'Right-Putamen', 'Right-Pallidum', 'Right-Hippocampus', 'Right-Amygdala',
        'Right-VentralDC', 'CC_Posterior', 'CC_Mid_Posterior', 'CC_Central',
        'CC_Mid_Anterior', 'CC_Anterior', 'Right-Cerebellum-Cortex',
        'Right-Cerebellum-White-Matter', 'Left-Cerebellum-Cortex',
        'Left-Cerebellum-White-Matter'] if c in df.columns]
    return dk + aseg


def func_feature_cols(df):
    """Connectivity edges, same cerebellar filter as the autism-vs-NT script."""
    cols = [c for c in df.columns if '/' in c and c.startswith('con_')]
    cols = [c for c in cols if 'Cerebellar' not in c or 'con_Cerebellar_Region1' in c]
    cols = [c for c in cols if 'Cerebellar_Region10' not in c]
    return cols


def load_anat(path=None):
    """Anat MRI z-scores (ANAT_FILE, or `path` if given) joined to curated-clinical phenotype.

    The z-score table carries neither age/sex nor a usable diagnosis column, so
    population_group + age_yrs + Sex + clean cohort come from the curated
    clinical TSVs, merged on the same canonical join key as the curated
    pipeline. Cortical GM volume (`_grayvol`) is renamed to `_volume` to match
    this script's feature/label conventions.
    """
    mri = pd.read_csv(path or ANAT_FILE, sep='\t', low_memory=False)
    mri['ID'] = mri['ID'].astype(str)
    mri = anat01._rename_freesurfer_cols(mri)
    mri = anat01.select_one_row_per_subject(mri)
    mri['_join_key'] = mri.apply(anat01._canonical_join_key_mri, axis=1)
    mri = mri.dropna(subset=['_join_key'])
    mri.columns = [c[:-len('_grayvol')] + '_volume' if c.endswith('_grayvol') else c
                   for c in mri.columns]

    clin = pd.read_csv(CLINICAL_FILE, low_memory=False)
    clin['ID'] = clin['ID'].astype(str)
    clin['_join_key'] = clin.apply(anat01._canonical_join_key_clusters, axis=1)
    clin = (clin.dropna(subset=['_join_key'])
                [['_join_key', 'cohort', 'population_group', 'age_yrs', 'Sex']]
                .drop_duplicates('_join_key'))

    # curated clinical is the phenotype source: drop any overlapping columns the
    # z-score MRI table carries so curated's population_group/age/sex/cohort win.
    mri = mri.drop(columns=['cohort', 'population_group', 'age_yrs', 'Sex'],
                   errors='ignore')
    merged = clin.merge(mri, on='_join_key', how='inner')
    print(f"  anat MRI x curated clinical: {len(merged)} subjects")
    return merged


def load_anat_noage():
    """load_anat() on the age-preserving (NOAGE_ANAT_FILE) table -- age-bin
    robustness check only (09_age_bin_regional_effect.py,
    10_age_bin_brain_maps.py). See NOAGE_ANAT_FILE docstring above."""
    return load_anat(path=NOAGE_ANAT_FILE)


def _ggseg_label(feat):
    """Map an anat feature column to a ggseg label + (atlas, metric)."""
    for metric in ('thickness', 'area', 'volume'):
        if feat.endswith('_' + metric) and feat[:3] in ('lh_', 'rh_'):
            hemi = 'left' if feat.startswith('lh_') else 'right'
            region = feat[3:-(len(metric) + 1)]
            return f'{region}_{hemi}', 'dk', metric
    return feat, 'aseg', 'volume'  # subcortical: keep raw label


def export_anat_ggseg_inputs(results, n_autism, n_nt):
    """Per (model, metric, atlas) CSV in the format 03_plot_*.R expects:
    headerless label,t_stat,p_val,cohens_d,p_fdr; FDR recomputed within metric."""
    rdir = os.path.join(OUTPUT_DIR, 'figures', 'r_input_files')
    Path(rdir).mkdir(parents=True, exist_ok=True)
    pd.DataFrame([{'n_autism': n_autism, 'n_nt': n_nt}]).to_csv(
        os.path.join(rdir, 'group_counts.csv'), index=False)

    for model_name, res_df in results.items():
        lab = res_df['feature'].map(_ggseg_label)
        df = res_df.assign(label=[x[0] for x in lab],
                           atlas=[x[1] for x in lab],
                           metric=[x[2] for x in lab])
        for (atlas, metric), grp in df.groupby(['atlas', 'metric']):
            grp = grp.copy()
            grp['p_fdr'] = multipletests(grp['p_value'], method='fdr_bh')[1]
            out = os.path.join(
                rdir, f't_stat_anat_{atlas}_{metric}_interaction_{model_name}.csv')
            grp[['label', 't', 'p_value', 'cohens_d', 'p_fdr']].to_csv(
                out, index=False, header=False)


def main():
    print("=" * 60)
    print("Age & Sex interaction analysis (group level)")
    print("=" * 60)

    summaries = []

    print("\nANATOMICAL")
    anat = load_anat()
    anat = prep_common(anat, 'population_group')
    n_aut, n_nt = int((anat['diag'] == 'Autism').sum()), int((anat['diag'] == 'NT').sum())
    print(f"  n={len(anat)}  Autism={n_aut} NT={n_nt}")
    feats = anat_feature_cols(anat)
    # Global size covariates: mean surface area / mean cortical volume per subject.
    # Regressing these out absorbs the all-region-shared (global) age x diagnosis
    # scaling so a region only survives on its region-specific interaction.
    area_cols = [c for c in feats if c.endswith('_area')]
    vol_cols = [c for c in feats if c.endswith('_volume') and c[:3] in ('lh_', 'rh_')]
    anat['glob_area'] = anat[area_cols].mean(axis=1)
    anat['glob_volume'] = anat[vol_cols].mean(axis=1)

    def anat_cov(f):
        atlas, metric = _ggseg_label(f)[1:]
        if metric == 'area':
            return 'glob_area'
        if metric == 'volume' and atlas == 'dk':
            return 'glob_volume'
        return None  # thickness + subcortical: no global size adjustment

    # FDR within each anatomical metric (thickness/area/cortical-vol/subcort-vol),
    # matching the autism-vs-NT anatomical pipeline.
    anat_family = lambda f: '_'.join(_ggseg_label(f)[1:])  # atlas_metric
    anat_sum, anat_res = run_models(anat, feats, 'anat',
                                    family_of=anat_family, cov_of=anat_cov)
    summaries += anat_sum
    export_anat_ggseg_inputs(anat_res, n_aut, n_nt)

    print("\nFUNCTIONAL")
    # ponytail: ~thousands of OLS fits x2 models, a few min. Vectorize only if
    # this becomes a bottleneck on reruns.
    func = pd.read_csv(FUNC_FILE)
    func = prep_common(func, 'population_group')
    print(f"  n={len(func)}  Autism={int((func['diag']=='Autism').sum())} "
          f"NT={int((func['diag']=='NT').sum())}")
    func_sum, _ = run_models(func, func_feature_cols(func), 'func')
    summaries += func_sum

    df_sum = pd.DataFrame(summaries)
    out = os.path.join(OUTPUT_DIR, 'age_sex_interaction_summary.csv')
    df_sum.to_csv(out, index=False)
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(df_sum.to_string(index=False))
    print(f"\nSaved: {out}")


if __name__ == '__main__':
    main()
